# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/EE/VC28/Audio_Viz_Project_Template.cache/wt [current_project]
set_property parent.project_path C:/EE/VC28/Audio_Viz_Project_Template.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VOICE_CAPTURER.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_DISPLAY.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Draw_Waveform.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Draw_Background.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/Voice_Scope_TOP.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_clk_div.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/TestWave_Gen.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_running_max.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_led_display_module.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_anode_display_module.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_dff.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/single_pulse.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/theme_selector.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/project_menu_screen.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_sound_bar.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/enemy_color_selector.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_bullet_color_selector.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/pseudo_wave_gen.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/custom_wave_module.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/sound_specs_screen.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_running_avg.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/my_running_min.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/game_texts.v
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/new/help_screen.v
}
read_vhdl -library xil_defaultlib {
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/VGA_CONTROL.vhd
  C:/EE/VC28/Audio_Viz_Project_Template.srcs/sources_1/imports/new/CLK_108M.vhd
  C:/Users/sdssa/OneDrive/Desktop/VGA-Text-Generator-master/VGA-Text-Generator.srcs/sources_1/new/Font_Rom.vhd
  C:/Users/sdssa/OneDrive/Desktop/VGA-Text-Generator-master/VGA-Text-Generator.srcs/sources_1/new/Pixel_On_Text.vhd
  C:/Users/sdssa/OneDrive/Desktop/VGA-Text-Generator-master/VGA-Text-Generator.srcs/sources_1/new/wrapper.vhd
  C:/Users/sdssa/OneDrive/Desktop/VGA-Text-Generator-master/VGA-Text-Generator.srcs/sources_1/new/Pixel_On_Text2.vhd
  C:/Users/sdssa/OneDrive/Desktop/VGA-Text-Generator-master/VGA-Text-Generator.srcs/sources_1/new/commonPak.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/EE/VC28/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/EE/VC28/Audio_Viz_Project_Template.srcs/constrs_1/imports/new/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Voice_Scope_TOP -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voice_Scope_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voice_Scope_TOP_utilization_synth.rpt -pb Voice_Scope_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
